
spring:
  profiles:
#    active: local
    active: development

  # Enabling Color Coded Output
  output:
    ansi:
      enabled: always

  # message
  messages:
    basename: i18n/exception
    encoding: UTF-8
