# PORT
server:
  port: 8080

spring:

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/SPRING_STUDY?useSSL=false&serverTimezone=UTC
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format-sql: true
    generate-ddl: false
    show-sql: false
    database: mysql

  redis:
    host: 127.0.0.1
    port: 6379
    password: P@ssw0rd

jwt:
  token:
    access-token-secret-key: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
    access-token-expire-length: 300000
    refresh-token-secret-key: cmVmcmVzaHRva2Vuc2VjcmV0a2V5Cg==
    refresh-token-expire-length: 6000000
